title: Chipprogrammer
short_title: CP
url: "https://chipprogrammer.github.io"
baseurl: "/amplify"
logo: "/static/img/chip.svg"
markdown: kramdown



paginate: 4
paginate_path: "/blog/page:num/"
gems: [jekyll-paginate, jekyll-gist]
