title: Chipprogrammer
author: Arun K Soman
url: "https://chipprogrammers.github.io"
baseurl: "/amplify"
logo: "/static/img/chip.svg"
markdown: kramdown
disqusEmbedd: "https://chipprogrammers.github.io/disqus-amp/"

google-analytics: UA-101566301-1
data-ad-client: xxxxxxxxxxxxx

paginate: 4
paginate_path: "/blog/page:num/"
gems: [jekyll-paginate, jekyll-gist]
disqus_shortname: https-chipprogrammers-github-io-pimate
